### ISSUE TITLE
HTTPError: 401 Client Error: Unauthorized for url: https://api.twitter.com/2/users/by/username/retroscifiart?user.fields=pinned_tweet_id

### ISSUE THREAD

**Issue by vserbu** [robertoszek/pleroma-bot#78] opened 2022-04-08 09:40 UTC
I recently changed my fediverse instance from mastodon to pleroma (soapboxfe). I try to install pleroma-bot and started with one bot but got this error:
...
ℹ 2022-04-08 09:38:23,560 - pleroma_bot - INFO - config path: /root/config.yml
ℹ 2022-04-08 09:38:23,561 - pleroma_bot - INFO - tweets temp folder: /root/tweets
ℹ 2022-04-08 09:38:23,572 - pleroma_bot - INFO - ======================================
ℹ 2022-04-08 09:38:23,572 - pleroma_bot - INFO - Processing user:       Retroscifiart
ℹ 2022-04-08 09:38:23,573 - pleroma_bot - INFO - It seems like pleroma-bot is running for the first time for this Twitter user: retroscifiart
✖ 2022-04-08 09:38:23,858 - pleroma_bot - ERROR - Exception occurred (cli.py:536)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pleroma_bot/cli.py", line 419, in main
    user = User(user_item, config, base_path)
  File "/usr/local/lib/python3.6/dist-packages/pleroma_bot/cli.py", line 189, in __init__
    self.pinned_tweet_id = self._get_pinned_tweet_id()
  File "/usr/local/lib/python3.6/dist-packages/pleroma_bot/_pin.py", line 239, in _get_pinned_tweet_id
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.twitter.com/2/users/by/username/retroscifiart?user.fields=pinned_tweet_id&expansions=pinned_tweet_id&tweet.fields=entities
[1]+  Exit 127                requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.twitter.com/2/users/by/username/retroscifiart?user.fields=pinned_tweet_id
...

**Comment by vserbu** [comment] 2022-04-08 09:48
This is my config.yml
...
pleroma_base_url: https://salocha.online
max_tweets: 10
twitter_token:  xxx
users:
- twitter_username: retroscifiart
  pleroma_username: Retroscifiart
  pleroma_token: xxx
visibility: "public"

**Comment by vserbu** [comment] 2022-04-08 10:05
I'm not sure about pleroma_token is it access token when using step 3 from here: https://tinysubversions.com/notes/mastodon-bot/

**Comment by robertoszek** [comment] 2022-04-08 14:07
> I'm not sure about pleroma_token is it access token when using step 3 from here: https://tinysubversions.com/notes/mastodon-bot/ (there is access token and refresh token).

Yeah, `pleroma_token`'s value should be the value of the `access_token`:
https://robertoszek.github.io/pleroma-bot/gettingstarted/beforerunning/#fediverse-tokens

> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.twitter.com/2/users/by/username/retroscifiart?user.fields=pinned_tweet_id&expansions=pinned_tweet_id&tweet.fields=entities

However, it looks like the issue it's with the `twitter_token`, for whatever reason.
Is it the same token that was working before? Please check there are no trailing spaces or something along those lines.

I've been trying to reproduce it with my tokens and the Twitter user you provided and so far I've not been able to run into a  HTTP 401.

It could be potentially an issue on Twitter's side: https://twittercommunity.com/t/401-unauthorized-response-when-using-client-search-all-tweets-tweepy/169478

You can try regenerating your Twitter tokens on the developer portal and see if that makes any difference, make sure your project also has [Elevated access](https://developer.twitter.com/en/portal/products/elevated).

**Comment by vserbu** [comment] 2022-04-08 15:09
You were right! I recreated API key and it is working. Another question, last time I had a visibility problem and you solved it with so RC version (1.0.3rc3: pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pleroma-bot==1.0.3rc3) but this link is not working any more.

**Comment by robertoszek** [comment] 2022-04-08 15:13
There has been some further fixes, the latest release candidate is 1.0.3rc10:
```
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pleroma-bot==1.0.3rc10
```

An stable release should be coming out soon but you can try running 1.0.3rc10 until then.

**Comment by vserbu** [comment] 2022-04-08 15:21
Tnx, I think it is working :)

**Comment by robertoszek** [comment] 2022-04-08 15:35
Great! If you run into any other problems, feel free to open a new issue. I'll close this one for now.
Have a nice day!

**Closed by robertoszek** 2022-04-08 15:35 UTC
Labels: wontfix
