### ISSUE TITLE
Gets stuck on "Processing tweets" for geo-blocked video

### ISSUE THREAD

**Issue by nemobis** [robertoszek/pleroma-bot#88] opened 2022-07-29 22:03 UTC
```
ℹ 2022-07-30 00:38:29,954 - pleroma_bot - INFO - Processing user:       108069358706528497
ℹ 2022-07-30 00:38:32,116 - pleroma_bot - INFO - tweets gathered:        5
Processing tweets...  \
```

The culprit appears to be https://nitter.it/CarolineVoaden/status/1552048550481203200#m which is a quote-tweet of some geo-blocked BBC video tweet which, when loaded on twitter.com in Finland, claims "This video is not available in your area".

**Comment by gigantuar** [comment] 2022-09-09 13:48
Did you ever find a way around this? I've tried adding a 403 check to _processing.py in addition to the existing 404 check but it doesn't seem to work.

**Comment by robertoszek** [comment] 2022-09-27 18:17
Right! Geo-blocked content will be a problem, I've not ran into one thus far so I completely missed taking them into account 😅

I've implemented a hotfix on 1.1.1rc1, you can give it a spin by running this command if you need it right now:
`pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pleroma-bot==1.1.1rc1`
The fix will be included on the next stable release as well.
Cheers!

**Comment by nemobis** [comment] 2022-09-27 18:53
Il 27/09/22 21:17, robertoszek ha scritto:
> I've implemented a hotfix on 1.1.1rc1, you can give it a spin by running this command if you need it right now:

Thanks! Unfortunately I don't have a real-world example of geoblocked 
tweet right now, but I guess I can just look for some sports content 
some day. ^_^

**Comment by gigantuar** [comment] 2022-09-28 16:11
Just updated to 1.1.1rc1 and will keep an eye on the logs for geoblocked warnings. One of the accounts I was trying to follow seemed to fail more so hopefully it won't be long before it gets tested.

**Comment by nemobis** [comment] 2022-11-18 08:21
I've not yet seen a case where the new code definitely failed, but I think it might have failed on this one (an LBC video): https://nitter.it/g_gosden/status/1588549524905394176#m / https://twitter.com/g_gosden/status/1588549524905394176#m .

The only hint I have is that an account was stuck for 2 weeks and now (running 1.1.1rc12) it finally posted all later posts except this one.

**Comment by robertoszek** [comment] 2022-11-18 15:47
Weird, I'm not able to reproduce any issue with that tweet and I don't see anything strange on the API response:
https://user-images.githubusercontent.com/1080963/202742858-9925eaed-4d9b-4bec-801d-d2d0143451c5.png

You suspect it's geoblocked for you or is it related to something else?

Ah, and does it fail/gets stuck if you tell it specifically to post that tweet on the config?

```
[...]
users:
- twitter_username: User1
  pleroma_username: MyPleromaUser1
  pleroma_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  tweet_ids:
    - 1588549524905394176
[...]
```

**Comment by nemobis** [comment] 2022-11-18 16:26
Il 18/11/22 17:47, robertoszek ha scritto:
> Ah, and does it fail/gets stuck if you tell it specifically to post that tweet on the config?

I'll try!

**Closed** 2023-01-02 15:51 UTC
Labels: bug
